"""phase 1 add file_mtime

Revision ID: 4ce239bbbb58
Revises: da5e125115a7
Create Date: 2026-05-18 17:05:49.750483

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4ce239bbbb58'
down_revision: str | None = 'da5e125115a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_files', sa.Column('file_mtime', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_files', 'file_mtime')
    # ### end Alembic commands ###
