"""phase 2 job query and candidate_json

Revision ID: 51a9732f1a50
Revises: 4ce239bbbb58
Create Date: 2026-05-18 17:34:05.664100

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '51a9732f1a50'
down_revision: str | None = 'da5e125115a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acquisition_jobs', sa.Column('query', sa.String(), nullable=True))
    op.add_column('acquisition_jobs', sa.Column('candidate_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acquisition_jobs', 'candidate_json')
    op.drop_column('acquisition_jobs', 'query')
    # ### end Alembic commands ###
