"""initial schema

Revision ID: da5e125115a7
Revises:
Create Date: 2026-05-18 16:34:45.925022

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'da5e125115a7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_ref', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('failure_class', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('musicbrainz_artist_id', sa.String(), nullable=True),
    sa.Column('id_algorithm_version', sa.Integer(), nullable=False),
    sa.Column('normalize_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rejected_ids',
    sa.Column('internal_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('internal_id')
    )
    op.create_table('albums',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('musicbrainz_release_id', sa.String(), nullable=True),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('id_algorithm_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('album_id', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('disc_number', sa.Integer(), nullable=True),
    sa.Column('musicbrainz_recording_id', sa.String(), nullable=True),
    sa.Column('id_algorithm_version', sa.Integer(), nullable=False),
    sa.Column('normalize_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('codec', sa.String(), nullable=False),
    sa.Column('container', sa.String(), nullable=False),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_ref', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('layout_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_files')
    op.drop_table('tracks')
    op.drop_table('albums')
    op.drop_table('rejected_ids')
    op.drop_table('artists')
    op.drop_table('acquisition_jobs')
    # ### end Alembic commands ###
